var dataPortfolio = {
  skillType: ["Backend", "Frontend", "CSS", "Database"],

  skill: [
    {
      name: "PHP",
      level: "advanced",
      experience: "4 Tahun",
      type: "backend",
      icon: "fab fa-php",
      description:
        "Sebagai seorang pengembang PHP tingkat lanjutan dengan pengalaman selama 4 tahun, saya memiliki keahlian dalam menciptakan aplikasi sederhana yang efektif dan efisien",
      project: [],
    },
    {
      name: "Laravel",
      level: "advanced",
      experience: "4 Tahun",
      type: "backend",
      description:
        "Berpengalaman dalam pengembangan dan pembuatan aplikasi menggunakan framework laravel pada aplikasi monolitik maupun microservice ",
      project: ["SIKN ANRI", "Regmus"],
      certificate: ["bwa"]
    },
    {
      name: "Yii",
      level: "advanced",
      experience: "2 Tahun",
      type: "backend",
      description:
        "Pengembang Yii tingkat lanjutan dengan pengalaman 2 tahun, fokus pada pengembangan website pemerintah menggunakan framework Yii1 dan Yii2.",
      project: ["AHU Online"],
    },
    {
      name: "Bootstrap",
      level: "advanced",
      experience: "3 Tahun",
      type: "css",
      description:
        "Berpengalaman dalam mengembangkan website dengan menggunakan framework bootstrap pada aplikasi monolitik maupun microservice, serta pengalaman dalam mengembangkan website pemerintah",
      project: ["Regmus", "AHU Online"],
    },
    {
      name: "Tailwind",
      level: "advanced",
      experience: "2 Tahun",
      type: "css",
      description:
        "Berpengalaman dalam pengembangan dalam melakukan slicing dari desain figma ke dalam kode HTML",
      project: ["Portal DPD RI", "Landingpage S-LINK"],
    },
    {
      name: "Mysqsl",
      level: "advanced",
      experience: "3 Tahun",
      type: "database",
      description:
        "Melakukan Normalisasi database, membuat query yang efektif dan efisien, melakukan backup database dan monitoring database",
      project: ["Regmus", "AHU Online"],
    },
    {
      name: "Jquery",
      level: "advanced",
      experience: "3 Tahun",
      type: "frontend",
      description:
        "Berpengalaman dalam pengembangan website menggunakan jquery untuk manipulasi DOM, AJAX, dan lain-lain",
      project: ["AHU Online"],
    },
    {
      name: "Javascript",
      level: "advanced",
      experience: "4 Tahun",
      type: "frontend",
      description:
        "Berpengalaman dalam pengembangan website menggunakan javascript untuk manipulasi DOM, AJAX, dan lain-lain",
      project: [],
    },
    {
      name: "HTML 5",
      level: "advanced",
      experience: "5 Tahun",
      type: "frontend",
      description: "Melakukan slicing dari desain figma ke dalam kode HTML",
      project: [],
    },
    {
      name: "CSS3",
      level: "advanced",
      experience: "5 Tahun",
      type: "frontend",
      description: "Melakukan slicing dan customisasi desain",
      project: [],
    },
    {
      name: "Vue Js",
      level: "intermediate",
      experience: "1 Tahun",
      type: "frontend",
      description:
        "Melakukan pembuatan aplikasi Toko Online menggunakan Vue Js",
      project: ["Toko Online"],
    },
    {
      name: "React Js",
      level: "intermediate",
      experience: "1 Tahun",
      type: "frontend",
      description:
        "Melakukan pengembangan pada website admin Finpay menggunakan React Js",
      project: ["Finpay"],
    },
    {
      name: "Next Js",
      level: "intermediate",
      experience: "6 Bulan",
      type: "frontend",
      description: "Melakukan recoding website PORTAL DPD RI",
      project: ["Cloning Portal DPD RI"],
    },
    {
      name: "Livewire",
      level: "intermediate",
      experience: "6 Bulan",
      type: "frontend",
      description:
        "Melakukan pembuatan aplikasi sederhana menggunakan livewire",
      project: ["Kasir"],
    },
    {
      name: "Dart",
      level: "intermediate",
      experience: "1 Tahun",
      type: "frontend",
      description: "Melakukan pengembangan aplikasi mobile menggunakan dart",
      project: ["OKE JEK", "S-LINK"],
    },
    {
      name: "Flutter",
      level: "intermediate",
      experience: "1 Tahun",
      type: "frontend",
      description: "Melakukan pengembangan aplikasi mobile menggunakan flutter",
      project: ["OKE JEK", "S-LINK"],
    },
    {
      name: "Postgresql",
      level: "intermediate",
      experience: "1.5 Tahun",
      type: "database",
      description: "Berpengalaman dalam mengeloal database postgresql",
      project: ["SIKN ANRI"],
    },
    {
      name: "Node Js",
      level: "beginner",
      experience: "6 Bulan",
      type: "backend",
      description:
        "Berpengalaman dalam pembuatan BOT Whatsapp, dan dalam tahap belajar untuk pengembangan website menggunakan node js",
      project: ["Crawling Data", "Bot Whatsapp"],
    },
    {
      name: "Python",
      level: "beginner",
      experience: "6 Bulan",
      type: "backend",
      description: "Melakukan crawling data menggunakan python",
      project: ["Crawling Data"],
    },
    {
      name: "Angular",
      level: "beginner",
      experience: "3 Bulan",
      type: "frontend",
      description: "Sedang dalam tahap pembelajaran",
      project: [],
    },
    {
      name: "Golang",
      level: "beginner",
      experience: "3 Bulan",
      type: "backend",
      description: "Sedang dalam tahap pembelajaran",
      project: [],
    },
    {
      name: "Java",
      level: "beginner",
      experience: "6 Bulan",
      type: "backend",
      description: "Sedang dalam tahap pembelajaran",
      project: ["Testing Socket Finpay"],
    },
    {
      name: "Mongo DB",
      level: "beginner",
      experience: "3 Bulan",
      type: "database",
      description:
        "Pengalaman dalam pembuatan database untuk aplikasi MERN (MongoDB, Express, React, Node) course",
      project: [],
    },
    {
      name: "Firebase",
      level: "beginner",
      experience: "1 Tahun",
      type: "database",
      description:
        "Pengalaman dalam pembuatan dan pengembangan aplikasi mobile menggunakan firebase",
      project: ["Landingpage S-LINK", "OKE JEK"],
    },
    {
      name: "CI",
      level: "beginner",
      experience: "3 Bulan",
      type: "backend",
      description: "Sedang dalam tahap pembelajaran",
      project: [],
    },
    {
      name: "Nuxt Js",
      level: "beginner",
      experience: "3 Bulan",
      description: "-",
      type: "frontend",
      project: ["SIKN ANRI"],
    },
    {
      name: "Typescript",
      level: "beginner",
      experience: "3 Bulan",
      type: "frontend",
      description: "-",
      project: [],
    },
    {
      name: "Express Js",
      level: "beginner",
      experience: "3 Bulan",
      type: "backend",
      description: "-",
      project: [],
    },
    {
      name: "Dot Net",
      level: "beginner",
      experience: "3 Bulan",
      type: "backend",
      description: "-",
      project: ["Portal DPD RI"],
    },
    {
      name: "Redis",
      level: "beginner",
      experience: "3 Bulan",
      type: "-",
      description: "Melakukan caching data pada aplikasi",
      project: ["SIKN ANRI"],
    },
    {
      name: "Alpine Js",
      level: "beginner",
      experience: "6 Bulan",
      type: "frontend",
      description: "-",
      project: ["Portal DPD RI", "Portfolio"],
    },
    {
      name: "Git",
      level: "tools",
      type: "-",
      experience: "3 Tahun",
      description: "-",
      project: [],
    },
    {
      name: "Github",
      level: "tools",
      experience: "3 Tahun",
      type: "-",
      description: "-",
      project: [],
    },
    {
      name: "Gitlab",
      level: "tools",
      experience: "3 Tahun",
      type: "-",
      description: "-",
      project: [],
    },
    {
      name: "VS Code",
      level: "tools",
      experience: "-",
      type: "-",
      description: "-",
      project: [],
    },
    {
      name: "Jira",
      level: "tools",
      experience: "-",
      type: "-",
      description:
        "Melakukan monitoring dan management project menggunakan Jira",
      project: [],
    },
    {
      name: "Minio",
      level: "tools",
      experience: "3 Bulan",
      type: "-",
      description: "Melakukan uploading file ke minio",
      project: ["SIKN ANRI"],
    },
    {
      name: "Keycloak",
      level: "tools",
      experience: "3 Bulan",
      type: "-",
      description:
        "Melakukan autentikasi dan management user menggunakan keycloak",
      project: ["SIKN ANRI"],
    },
    {
      name: "Solr",
      level: "tools",
      experience: "3 Bulan",
      type: "-",
      description: "Melakukan searching data menggunakan solr",
      project: ["SIKN ANRI"],
    },
    {
      name: "Lumen",
      level: "beginner",
      experience: "6 Bulan",
      type: "backend",
      description: "Membuat API finpay menggunakan lumen",
      project: ["Finpay"],
    },
  ],

  experience: [
    {
      name: "PT. Microvac Indonesia",
      job: "Fullstack Developer",
      description: "Sebagai seorang pengembang website, saya bertanggung jawab dalam pengembangan dan pembuatan website dari sisi frontend dan backend, serta melakukan maintenance, memperbaiki bug pada website yang pemerintah. Baik itu website monolitik maupun microservice. serta melakukan pengembangan aplikasi lainnya.",
      start: "Juli 2021",
      end: "Sekarang",
      status: "Fulltime",
    },
    {
      name: "PT. Ruby Permata Indonesia",
      job: "Fullstack Developer",
      description: "Sebagai seorang pengembang website, saya bertanggung jawab dalam pengembangan dan pembuatan website aplikasi quiz online, serta melakukan maintenance, memperbaiki bug pada website admin finpay.",
      start: "November 2021",
      end: "September 2022",
      status: "Parttime",
    },
    {
      name: "Lion of Informatics",
      job: "Backend Developer",
      description: "Sebagai seorang pengembang backend, saya bertanggung jawab dalam pengembangan dan pembuatan API dan Admin Panel untuk aplikasi Wedding Invitation.",
      start: "Oktober 2020",
      end: "Juli 2021",
      status: "Fulltime",
    },
    {
      name: "Technophoria",
      job: "Tester",
      description: "Sebagai seorang tester, saya bertanggung jawab dalam melakukan testing pada aplikasi yang dibuat oleh perusahaan.",
      start: "November 2018",
      end: "Januari 2019",
      status: "Praktik Kerja Lapangan",
    },
    {
      name: "Hotel Safira",
      job: "IT Support",
      description: "Sebagai seorang IT Support, saya bertanggung jawab dalam melakukan maintenance pada komputer, serta melakukan instalasi software dan hardware.",
      start: "Febriari 2019",
      end: "Mei 2019",
      status: "Praktik Kerja Lapangan",
    }
  ],

  education: [
    {
      name: "Universitas Sangga Buana YPKP",
      major: "Teknik Informatika",
      description: "Oktober 2022 - Now \n belajar tentang dasar pemrograman, dan pembuatan aplikasi berbasis web dan mobile",
    },
    {
      name: "SMK Negeri 2 Magelang",
      major: "Rekayasa Perangkat Lunak",
      description: "Juni 2017 - Juli 2020 \n Belajar tentang dasar pemrograman, algoritma, dan struktur data",
    }
  ],

  project: [
    {
      name: "AHU Online",
      thumbnail: "",
      description: "Website Direktorat Jenderal Administrasi Hukum Umum adalah unit kerja yang berada di bawah dan bertanggung jawab kepada Menteri Hukum dan Hak Asasi Manusia Republik Indonesia yang mempunyai tugas menyelenggarakan urusan di bidang administrasi hukum umum.",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Kewarganegaraan",
      thumbnail: "",
      description: "Website untun mengubah status kewarganegaraan",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Pewarganegaraan",
      thumbnail: "",
      description: "Website untuk proses alih status dari Warga Negara Asing (WNA) menjadi Warga Negara Indonesia (WNI) melalui berbagai dasar permohonan, termasuk naturalisasi yang diajukan oleh WNA tersebut.",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "E-Office",
      thumbnail: "",
      description: "Website untuk melakukan pengajuan surat keterangan dari kantor",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Sistem Administrasi Badan Usaha",
      thumbnail: "",
      description: "Website untuk melakukan pendafataran, perubahan, dan penghapusan badan usaha",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Sistem Administrasi Badan Hukum",
      thumbnail: "",
      description: "Website untuk melakukan pendafataran, perubahan, dan penghapusan badan hukum",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Portal AHU",
      thumbnail: "",
      description: "Website untuk memberikan informasi tentang Direktorat Jenderal Administrasi Hukum Umum",
      technology: ["YII", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Portal DPD RI",
      thumbnail: "",
      description: "Website untuk memberikan informasi tentang Dewan Perwakilan Daerah Republik Indonesia",
      technology: ["Tailwind", "Alpine Js", "Dot Net"],
    },
    {
      name: "Regmus",
      thumbnail: "",
      description: "Website ini digunakan untuk melakukan pendaftaran museum secara online",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "SIKN ANRI",
      thumbnail: "",
      description: "Website ini digunakan untuk mengelola arsip nasional",
      technology: ["Laravel", "Postgresql", "Nuxt Js", "Minio", "Keycloak", "Solr", "Redis"],
    },
    {
      name: "Finpay",
      thumbnail: "",
      description: "Website ini digunakan untuk melakukan pembayaran secara online",
      technology: ["Mysql", "React Js", "Lumen"],
    },
    {
      name: "Viding",
      thumbnail: "",
      description: "Website ini digunakan untuk melakukan melakukan virtual wedding dan invitation",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Toko Online",
      thumbnail: "",
      description: "Website ini digunakan untuk melakukan pembelian secara online",
      technology: ["Vue Js", "Bootstrap", "Mysql", "Laravel"],
    },
    {
      name: "OKE JEK",
      thumbnail: "",
      description: "Aplikasi Mobile dengan flutter digunakan untuk melakukan pesanan ojek online serta pesanan makanan",
      technology: ["Flutter", "Dart", "Firebase"],
    },
    {
      name: "S-LINK",
      thumbnail: "",
      description: "Aplikasi Mobile dengan flutter digunakan untuk melakukan memendekkan link",
      technology: ["Flutter", "Dart", "Firebase"],
    },
    {
      name: "Kasir",
      thumbnail: "",
      description: "Aplikasi sederhana sebagai kasir, dan memonitori stok gudang",
      technology: ["Livewire", "Bootstrap", "Mysql", "Laravel"],
    },
    {
      name: "Landingpage S-LINK",
      thumbnail: "",
      description: "Landingpage untuk aplikasi S-LINK dibangun dengan menggunakan tailwind dan remix js",
      technology: ["Tailwind", "Remix Js", "Prisma"],
    },
    {
      name: "Quiz",
      thumbnail: "",
      description: "Website untuk melakukan management quiz online",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Sinopsis",
      thumbnail: "",
      description: "Website untuk melakukan memilih ketua OSIS secara online",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Ecomplain",
      thumbnail: "",
      description: "Website untuk melakukan pengaduan secara online",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Travel",
      thumbnail: "",
      description: "Website untuk melakukan pemesanan tiket travel secara online",
      technology: ["Laravel", "Bootstrap", "Mysql", "Jquery"],
    },
    {
      name: "Clone Portal DPD RI",
      thumbnail: "",
      description: "Website untuk melakukan cloning website portal DPD RI",
      technology: ["Next Js", "Tailwind", "Graph QL"],
    }
  ],

  certificate: [
    {
      'image': './assets/images/certificate/fullstack-web-dev.jpg',
      'name': 'BWA - Fullstack Web Developer, Travel',
    },
    {
      'image': './assets/images/certificate/e-commerce.jpg',
      'name': 'BWA - Laravel E-Commerce',
    },
    {
      'image': './assets/images/certificate/laravel-vue.jpg',
      'name': 'BWA - Laravel Vue JS Toko Online',
    },
    {
      'image': './assets/images/certificate/javascript-intermediate.jpg',
      'name': 'Sololearn - Javascript Intermediate',
    },
    {
      'image': './assets/images/certificate/javascript.jpg',
      'name': 'Sololearn - Javascript',
    },
    {
      'image': './assets/images/certificate/css.jpg',
      'name': 'Sololearn - CSS',
    },
    {
      'image': './assets/images/certificate/html.jpg',
      'name': 'Sololearn - HTML',
    },
    {
      'image': './assets/images/certificate/jquery.jpg',
      'name': 'Sololearn - Jquery',
    },
    {
      'image': './assets/images/certificate/php.jpg',
      'name': 'Sololearn - PHP',
    },
    {
      'image': './assets/images/certificate/responsive-web.jpg',
      'name': 'Sololearn - Responsive web design',
    },
    {
      'image': './assets/images/certificate/sql.jpg',
      'name': 'Sololearn - Sql',
    }
  ]
};